INSERT INTO CLIENTE VALUES (NULL,'Pepito1','Perez1','1231231',1231231,'pepito1@gmail.com');
INSERT INTO CLIENTE VALUES (NULL,'Pepito2','Perez2','1231232',1231232,'pepito2@gmail.com');
INSERT INTO CLIENTE VALUES (NULL,'Pepito3','Perez3','1231233',1231233,'pepito3@gmail.com');
INSERT INTO CLIENTE VALUES (NULL,'Pepito4','Perez4','1231234',1231234,'pepito4@gmail.com');

INSERT INTO PRODUCTO VALUES (NULL,'Producto #1',123.36);
INSERT INTO PRODUCTO VALUES (NULL,'Producto #2',1231.36);
INSERT INTO PRODUCTO VALUES (NULL,'Producto #3',1223.36);
INSERT INTO PRODUCTO VALUES (NULL,'Producto #4',12233.36);

INSERT INTO Venta VALUES (NULL,1,CURRENT_DATE());
INSERT INTO Venta VALUES (NULL,1,CURRENT_DATE());
INSERT INTO Venta VALUES (NULL,3,CURRENT_DATE());
INSERT INTO Venta VALUES (NULL,2,CURRENT_DATE());

INSERT INTO DetalleVenta VALUES (NULL,1,1);
INSERT INTO DetalleVenta VALUES (NULL,2,1);
INSERT INTO DetalleVenta VALUES (NULL,3,1);
INSERT INTO DetalleVenta VALUES (NULL,4,1);
INSERT INTO DetalleVenta VALUES (NULL,1,2);
INSERT INTO DetalleVenta VALUES (NULL,2,2);
INSERT INTO DetalleVenta VALUES (NULL,3,2);
INSERT INTO DetalleVenta VALUES (NULL,4,2);
INSERT INTO DetalleVenta VALUES (NULL,1,3);
INSERT INTO DetalleVenta VALUES (NULL,2,4);
INSERT INTO DetalleVenta VALUES (NULL,3,4);
INSERT INTO DetalleVenta VALUES (NULL,4,4);
